# Generated by Django 4.1.4 on 2022-12-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0002_room_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="amenity",
            options={"verbose_name_plural": "어매니티"},
        ),
        migrations.AlterModelOptions(
            name="room",
            options={"verbose_name_plural": "숙소"},
        ),
        migrations.AlterField(
            model_name="room",
            name="amenities",
            field=models.ManyToManyField(blank=True, null=True, to="rooms.amenity"),
        ),
    ]
