databases:
  - name: accomo-sun-backend
    databaseName: accomo-sun-backend
    user: accomo-sun-backend
    region: singapore

services:
  - type: web
    name: accomo-sun-backend
    env: python
    region: singapore
    buildCommand: "./build.sh"
    startCommand: "gunicorn mysite.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: accomo-sun-backend
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
