# Generated by Django 4.1.4 on 2022-12-21 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "experiences",
            "0002_experience_category_alter_experience_description_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="experience",
            options={"verbose_name_plural": "놀거리"},
        ),
        migrations.AlterModelOptions(
            name="perk",
            options={"verbose_name_plural": "특전"},
        ),
    ]
