# Generated by Django 4.1.4 on 2022-12-21 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("medias", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="photo",
            options={"verbose_name_plural": "사진"},
        ),
        migrations.AlterModelOptions(
            name="video",
            options={"verbose_name_plural": "동영상"},
        ),
    ]
